import Foundation
import InputMethodKit
import AppKit
import Carbon
import LingoPulseIMECore

// LingoPulseIMEController intercepts keystrokes via InputMethodKit's keybinding
// approach (approach 1): printable text arrives via inputText(_:client:) and
// commands (Enter, Escape, arrows, Backspace) arrive via didCommand(by:client:).
//
// Phase 6 — Tab accept / Esc dismiss / arrow cycle
//   didCommand handles four selectors when SuggestionWindow is visible:
//     insertTab:        → accept current edit (consumed, returns true)
//     cancelOperation:  → dismiss + clear buffer (consumed, returns true)
//     moveDown:         → cycle selection down (consumed, returns true)
//     moveUp:           → cycle selection up (consumed, returns true)
//   Any other selector → dismiss window + fall through (return false) so the
//   host application still receives the key and the existing buffer-reset logic
//   continues to work.
//
// Replace mechanism: insertText(_:replacementRange:)
//   We pass NSRange(location: cursor - bufferLength, length: bufferLength) so the
//   IMK client replaces exactly the typed buffer with the refined text.  This is
//   preferred over CGEvent backspace sequences because:
//     1. It is atomic — no flickering from individual delete events.
//     2. It does not fire additional didCommand calls that would re-enter our logic.
//     3. It works correctly in clients that use undo coalescing (TextEdit, Notes).
//   Caveat: some custom IMK clients may not support a non-zero replacement range and
//   will fall back to inserting at the cursor.  In practice, all Cocoa text views
//   (NSTextView, UITextView, WebKit) honour the replacement range.  If future testing
//   reveals a problem with a specific client we can fall back to CGEvent backspaces
//   for that client.
@objc(LingoPulseIMEController)
final class LingoPulseIMEController: IMKInputController {

    // MARK: - State

    private var session = TypingSession()
    private let debouncer = Debouncer(interval: 1.5)
    private let daemon = IMEDaemonClient()
    private let suggestionWindow = SuggestionWindow()
    private let preferences = IMEPreferences()
    private var inFlight = false

    // The original text that produced the current suggestion set, and its length
    // in UTF-16 code units (matching NSRange/IMK conventions).
    private var originalText: String = ""
    private var bufferUTF16Length: Int = 0

    // Retains the app-activation observer token so it lives as long as the controller.
    private var appActivationObserver: NSObjectProtocol?

    // MARK: - Lifecycle

    override init!(server: IMKServer!, delegate: Any!, client inputClient: Any!) {
        super.init(server: server, delegate: delegate, client: inputClient)
        setupSuggestionCallbacks()
        setupAppDiagnostics()
    }

    override func activateServer(_ sender: Any!) {
        session.reset()
    }

    override func deactivateServer(_ sender: Any!) {
        debouncer.cancel()
        session.reset()
        suggestionWindow.hide()
        clearSuggestionState()
    }

    // MARK: - IMKServerInput (keybinding approach)

    /// Receives printable characters that did not map to a keybinding action.
    /// Returns false so the character is passed through to the active application.
    override func inputText(_ string: String!, client sender: Any!) -> Bool {
        guard let text = string, !text.isEmpty else { return false }
        session.append(text)

        debouncer.schedule { [weak self] in
            self?.requestRefine()
        }
        return false
    }

    /// Receives special-key commands generated by the system keybinding table.
    ///
    /// When the SuggestionWindow is visible:
    ///   - Tab (insertTab:)        → accept current edit, consume the key.
    ///   - Esc (cancelOperation:)  → dismiss + clear buffer, consume the key.
    ///   - ↓  (moveDown:)          → cycle selection down, consume the key.
    ///   - ↑  (moveUp:)            → cycle selection up, consume the key.
    ///   - anything else           → dismiss + fall through (return false).
    ///
    /// When the SuggestionWindow is not visible, all selectors fall through and
    /// the existing buffer-reset logic runs normally.
    override func didCommand(by aSelector: Selector!, client sender: Any!) -> Bool {
        if suggestionWindow.isVisible {
            switch aSelector {
            case #selector(NSResponder.insertTab(_:)):
                suggestionWindow.handleTabKey()
                return true  // consumed: the host app must not receive Tab

            case #selector(NSResponder.cancelOperation(_:)):
                suggestionWindow.handleEscapeKey()
                // Buffer was already cleared by onDismiss callback.
                return true  // consumed

            case #selector(NSResponder.moveDown(_:)):
                suggestionWindow.cycleDown()
                return true  // consumed

            case #selector(NSResponder.moveUp(_:)):
                suggestionWindow.cycleUp()
                return true  // consumed

            default:
                // Any other key (e.g. Return, Backspace, Left arrow) dismisses
                // the panel and falls through so the host app sees the key.
                suggestionWindow.hide()
                clearSuggestionState()
                // fall through to the navigation-reset block below
            }
        }

        switch aSelector {
        // Navigation / commit / cancel — reset session and dismiss any suggestion.
        case #selector(NSResponder.insertNewline(_:)),                      // Return
             #selector(NSResponder.insertLineBreak(_:)),                    // Ctrl-Return
             #selector(NSResponder.cancelOperation(_:)),                    // Escape / Cmd-.
             #selector(NSResponder.deleteBackward(_:)),                     // Backspace
             #selector(NSResponder.deleteForward(_:)),                      // Delete (fn-Backspace)
             #selector(NSResponder.moveLeft(_:)),                           // Left arrow
             #selector(NSResponder.moveRight(_:)),                          // Right arrow
             #selector(NSResponder.moveUp(_:)),                             // Up arrow
             #selector(NSResponder.moveDown(_:)),                           // Down arrow
             #selector(NSResponder.moveToBeginningOfLine(_:)),              // Cmd-Left / Home
             #selector(NSResponder.moveToEndOfLine(_:)),                    // Cmd-Right / End
             #selector(NSResponder.moveToBeginningOfDocument(_:)),          // Cmd-Up
             #selector(NSResponder.moveToEndOfDocument(_:)),                // Cmd-Down
        // Modifier combos — Shift selection (cursor moves → caret position changed)
             #selector(NSResponder.moveLeftAndModifySelection(_:)),         // Shift-Left
             #selector(NSResponder.moveRightAndModifySelection(_:)),        // Shift-Right
             #selector(NSResponder.moveUpAndModifySelection(_:)),           // Shift-Up
             #selector(NSResponder.moveDownAndModifySelection(_:)),         // Shift-Down
             #selector(NSResponder.moveToLeftEndOfLine(_:)),                // Cmd-Left (RTL / some apps)
             #selector(NSResponder.moveToRightEndOfLine(_:)),               // Cmd-Right (RTL / some apps)
             #selector(NSResponder.moveToBeginningOfDocumentAndModifySelection(_:)),
             #selector(NSResponder.moveToEndOfDocumentAndModifySelection(_:)),
             #selector(NSResponder.moveToLeftEndOfLineAndModifySelection(_:)),
             #selector(NSResponder.moveToRightEndOfLineAndModifySelection(_:)),
        // Modifier combos — Option word navigation
             #selector(NSResponder.moveWordLeft(_:)),                       // Option-Left
             #selector(NSResponder.moveWordRight(_:)),                      // Option-Right
             #selector(NSResponder.moveWordLeftAndModifySelection(_:)),     // Shift-Option-Left
             #selector(NSResponder.moveWordRightAndModifySelection(_:)),    // Shift-Option-Right
        // Modifier combos — word / line deletion
             #selector(NSResponder.deleteWordBackward(_:)),                 // Option-Backspace
             #selector(NSResponder.deleteWordForward(_:)),                  // Option-Delete
             #selector(NSResponder.deleteToBeginningOfLine(_:)):            // Cmd-Backspace
            debouncer.cancel()
            session.reset()
            suggestionWindow.hide()
            clearSuggestionState()

        default:
            break
        }
        return false
    }

    override func commitComposition(_ sender: Any!) {
        debouncer.cancel()
        session.reset()
        clearSuggestionState()
    }

    // MARK: - Suggestion window callbacks

    private func setupSuggestionCallbacks() {
        suggestionWindow.onAccept = { [weak self] index in
            self?.acceptEdit(at: index)
        }
        suggestionWindow.onDismiss = { [weak self] in
            self?.debouncer.cancel()
            self?.session.reset()
            self?.clearSuggestionState()
        }
    }

    // MARK: - Accept logic

    /// Accept the edit at `index`: replace the buffered text in the host field
    /// with the refined text for that edit, then dismiss the suggestion panel.
    private func acceptEdit(at index: Int) {
        let edits = suggestionWindow.edits
        guard index < edits.count else {
            suggestionWindow.hide()
            clearSuggestionState()
            return
        }
        let edit = edits[index]
        let replacement = edit.to_text

        replaceBuffer(with: replacement)

        suggestionWindow.hide()
        debouncer.cancel()
        session.reset()
        clearSuggestionState()
    }

    /// Replace the typed buffer in the host text field with `replacement`.
    ///
    /// Mechanism: insertText(_:replacementRange:) with an NSRange that spans
    /// the last `bufferUTF16Length` UTF-16 code units before the cursor.
    ///
    /// We query selectedRange() (available on all IMKTextInput clients) to find
    /// the current insertion point.  NSRange uses UTF-16 offsets, which match
    /// what NSTextView / WebKit / etc. use internally.
    private func replaceBuffer(with replacement: String) {
        guard let textClient = client() as? (IMKTextInput & NSObject) else {
            IMELog.error("replaceBuffer — no IMKTextInput client, skipping")
            return
        }

        let len = bufferUTF16Length
        guard len > 0 else { return }

        // IMKTextInput.selectedRange() returns the current selection/cursor in
        // UTF-16 code units.  For a collapsed cursor, .length == 0 and .location
        // is the insertion point.
        let sel = textClient.selectedRange()
        let cursor: Int

        if sel.location == NSNotFound {
            // Client does not report a position — fall back to the sentinel range
            // that means "replace the current selection / cursor" in IMK.
            // This inserts at cursor without deleting anything, which is wrong for
            // our replacement use case.  Log and bail.
            IMELog.error("replaceBuffer — selectedRange returned NSNotFound, skipping")
            return
        } else {
            cursor = sel.location + sel.length  // end of selection (= insertion point)
        }

        guard cursor >= len else {
            IMELog.error("replaceBuffer — cursor(\(cursor)) < bufferLen(\(len)), skipping")
            return
        }

        let replRange = NSRange(location: cursor - len, length: len)
        textClient.insertText(replacement, replacementRange: replRange)
        IMELog.info("replaced range \(replRange) with \"\(replacement)\"")
    }

    // MARK: - Daemon

    private func requestRefine() {
        guard !inFlight, !session.isEmpty else { return }

        // Skip refinement when the system is reading from a secure input field
        // (e.g. password prompt). macOS suspends IMEs automatically in that case,
        // but we add an explicit guard as a defence-in-depth measure so no
        // partial buffer contents are sent to the daemon.
        if IsSecureEventInputEnabled() {
            IMELog.debug("secure input active — skipping refine")
            return
        }

        let snapshot = session.buffer
        let appName = NSWorkspace.shared.frontmostApplication?.localizedName ?? "Unknown"

        // Honour the user's per-app exclusion list (read from shared UserDefaults).
        if preferences.excludedApps.contains(appName) {
            IMELog.debug("\(appName) is excluded — skipping refine")
            return
        }

        // Capture caret rect before going async.
        let caretRect = caretScreenRect()

        inFlight = true
        Task { @MainActor in
            defer { self.inFlight = false }
            do {
                let resp = try await self.daemon.refine(text: snapshot, app: appName)
                IMELog.info("refine → \(resp.edits.count) edits, refined=\(String(resp.refined.suffix(60)))")
                if !resp.edits.isEmpty {
                    // Store the context needed to perform replacement.
                    self.originalText = snapshot
                    self.bufferUTF16Length = snapshot.utf16.count
                    self.suggestionWindow.show(edits: resp.edits, caretScreenRect: caretRect)
                }
            } catch {
                IMELog.error("refine error \(error)")
            }
        }
    }

    private func clearSuggestionState() {
        originalText = ""
        bufferUTF16Length = 0
    }

    // MARK: - App diagnostics

    /// Subscribe to NSWorkspace.didActivateApplicationNotification and log a one-line
    /// diagnostic for every app switch. Helps identify which apps accept IME input.
    ///
    /// Output format (visible in Console.app or `log stream`):
    ///   LingoPulseIME [AppDiag]: active app: Slack (com.tinyspeck.slackmacgap) | policy: regular | IME input likely: YES
    ///   LingoPulseIME [AppDiag]: active app: iTerm2 (com.googlecode.iterm2) | policy: regular | IME input likely: NO (excluded)
    private func setupAppDiagnostics() {
        appActivationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] notification in
            guard let app = notification.userInfo?[NSWorkspace.applicationUserInfoKey]
                    as? NSRunningApplication else { return }
            self?.logAppActivation(app)
        }
    }

    private func logAppActivation(_ app: NSRunningApplication) {
        let name = app.localizedName ?? "Unknown"
        let bundleID = app.bundleIdentifier ?? "?"

        let policyString: String
        switch app.activationPolicy {
        case .regular:    policyString = "regular"
        case .accessory:  policyString = "accessory"
        case .prohibited: policyString = "prohibited"
        @unknown default: policyString = "unknown"
        }

        let excluded = preferences.excludedApps.contains(name)

        let imeNote: String
        if excluded {
            imeNote = "NO (excluded)"
        } else if app.activationPolicy == .regular {
            imeNote = "YES"
        } else {
            imeNote = "NO (policy: \(policyString))"
        }

        IMELog.debug("[AppDiag] active app: \(name) (\(bundleID)) | policy: \(policyString) | IME input likely: \(imeNote)")
    }

    deinit {
        if let obs = appActivationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(obs)
        }
    }

    /// Asks the current IMK client for the line-height rect at character index 0
    /// (the insertion point when there is no inline session).
    /// Returns .zero when the client does not provide a usable rect.
    private func caretScreenRect() -> NSRect {
        guard let textClient = client() as? (IMKTextInput & NSObject) else {
            return .zero
        }
        var lineRect = NSRect.zero
        // The return value is the attributes dict; the rect is the inout param.
        _ = textClient.attributes(forCharacterIndex: 0,
                                  lineHeightRectangle: &lineRect)
        return lineRect
    }
}
