import Foundation
import InputMethodKit
import AppKit
import LingoPulseIMECore

// LingoPulseIMEController intercepts keystrokes via InputMethodKit's keybinding
// approach (approach 1): printable text arrives via inputText(_:client:) and
// commands (Enter, Escape, arrows, Backspace) arrive via didCommand(by:client:).
// All events are passed through (return false) so the host application receives
// them unchanged. The only side-effect is maintaining a TypingSession buffer so
// that Phase 3 can trigger the daemon when enough words accumulate.
@objc(LingoPulseIMEController)
final class LingoPulseIMEController: IMKInputController {

    // MARK: - State

    private var session = TypingSession()
    private let debouncer = Debouncer(interval: 1.5)
    private let daemon = IMEDaemonClient()
    private let suggestionWindow = SuggestionWindow()
    private var inFlight = false

    // MARK: - Lifecycle

    override init!(server: IMKServer!, delegate: Any!, client inputClient: Any!) {
        super.init(server: server, delegate: delegate, client: inputClient)
    }

    override func activateServer(_ sender: Any!) {
        session.reset()
    }

    override func deactivateServer(_ sender: Any!) {
        debouncer.cancel()
        session.reset()
        suggestionWindow.hide()
    }

    // MARK: - IMKServerInput (keybinding approach)

    /// Receives printable characters that did not map to a keybinding action.
    /// Returns false so the character is passed through to the active application.
    override func inputText(_ string: String!, client sender: Any!) -> Bool {
        guard let text = string, !text.isEmpty else { return false }
        session.append(text)

        debouncer.schedule { [weak self] in
            self?.requestRefine()
        }
        return false
    }

    /// Receives special-key commands generated by the system keybinding table.
    /// Resets the session buffer for navigation/commit/cancel actions and
    /// modifier combos (Shift-selection, Option-word-nav, Option-word-delete,
    /// Cmd-line-delete). Returns false so the key is passed through to the
    /// active application.
    override func didCommand(by aSelector: Selector!, client sender: Any!) -> Bool {
        switch aSelector {
        // Tab: Phase 6 will accept the suggestion; for now log + dismiss.
        case #selector(NSResponder.insertTab(_:)):
            if suggestionWindow.isVisible {
                suggestionWindow.handleTabKey()
                return false  // pass through so app still receives Tab
            }

        // Navigation / commit / cancel — reset session and dismiss any suggestion.
        case #selector(NSResponder.insertNewline(_:)),                      // Return
             #selector(NSResponder.insertLineBreak(_:)),                    // Ctrl-Return
             #selector(NSResponder.cancelOperation(_:)),                    // Escape / Cmd-.
             #selector(NSResponder.deleteBackward(_:)),                     // Backspace
             #selector(NSResponder.deleteForward(_:)),                      // Delete (fn-Backspace)
             #selector(NSResponder.moveLeft(_:)),                           // Left arrow
             #selector(NSResponder.moveRight(_:)),                          // Right arrow
             #selector(NSResponder.moveUp(_:)),                             // Up arrow
             #selector(NSResponder.moveDown(_:)),                           // Down arrow
             #selector(NSResponder.moveToBeginningOfLine(_:)),              // Cmd-Left / Home
             #selector(NSResponder.moveToEndOfLine(_:)),                    // Cmd-Right / End
             #selector(NSResponder.moveToBeginningOfDocument(_:)),          // Cmd-Up
             #selector(NSResponder.moveToEndOfDocument(_:)),                // Cmd-Down
        // Modifier combos — Shift selection (cursor moves → caret position changed)
             #selector(NSResponder.moveLeftAndModifySelection(_:)),         // Shift-Left
             #selector(NSResponder.moveRightAndModifySelection(_:)),        // Shift-Right
             #selector(NSResponder.moveUpAndModifySelection(_:)),           // Shift-Up
             #selector(NSResponder.moveDownAndModifySelection(_:)),         // Shift-Down
             #selector(NSResponder.moveToLeftEndOfLine(_:)),                // Cmd-Left (RTL / some apps)
             #selector(NSResponder.moveToRightEndOfLine(_:)),               // Cmd-Right (RTL / some apps)
             #selector(NSResponder.moveToBeginningOfDocumentAndModifySelection(_:)),
             #selector(NSResponder.moveToEndOfDocumentAndModifySelection(_:)),
             #selector(NSResponder.moveToLeftEndOfLineAndModifySelection(_:)),
             #selector(NSResponder.moveToRightEndOfLineAndModifySelection(_:)),
        // Modifier combos — Option word navigation
             #selector(NSResponder.moveWordLeft(_:)),                       // Option-Left
             #selector(NSResponder.moveWordRight(_:)),                      // Option-Right
             #selector(NSResponder.moveWordLeftAndModifySelection(_:)),     // Shift-Option-Left
             #selector(NSResponder.moveWordRightAndModifySelection(_:)),    // Shift-Option-Right
        // Modifier combos — word / line deletion
             #selector(NSResponder.deleteWordBackward(_:)),                 // Option-Backspace
             #selector(NSResponder.deleteWordForward(_:)),                  // Option-Delete
             #selector(NSResponder.deleteToBeginningOfLine(_:)):            // Cmd-Backspace
            debouncer.cancel()
            session.reset()
            suggestionWindow.hide()

        default:
            break
        }
        return false
    }

    override func commitComposition(_ sender: Any!) {
        debouncer.cancel()
        session.reset()
    }

    // MARK: - Daemon

    private func requestRefine() {
        guard !inFlight, !session.isEmpty else { return }
        let snapshot = session.buffer
        let appName = NSWorkspace.shared.frontmostApplication?.localizedName ?? "Unknown"

        // Capture caret rect before going async.
        // attributes(forCharacterIndex:lineHeightRectangle:) returns the font/
        // orientation dict; the caret rect comes via the inout lineRect parameter.
        // The rect is in AppKit screen coordinates: origin at bottom-left of the
        // primary display, Y increasing upward.
        let caretRect = caretScreenRect()

        inFlight = true
        Task { @MainActor in
            defer { self.inFlight = false }
            do {
                let resp = try await self.daemon.refine(text: snapshot, app: appName)
                NSLog("LingoPulseIME: refine → \(resp.edits.count) edits, refined=\(resp.refined.suffix(60))")
                if !resp.edits.isEmpty {
                    self.suggestionWindow.show(edits: resp.edits, caretScreenRect: caretRect)
                }
                // Phase 6 will handle Tab-accept
            } catch {
                NSLog("LingoPulseIME: refine error \(error)")
            }
        }
    }

    /// Asks the current IMK client for the line-height rect at character index 0
    /// (the insertion point when there is no inline session).
    /// Returns .zero when the client does not provide a usable rect.
    private func caretScreenRect() -> NSRect {
        guard let textClient = client() as? (IMKTextInput & NSObject) else {
            return .zero
        }
        var lineRect = NSRect.zero
        // The return value is the attributes dict; the rect is the inout param.
        _ = textClient.attributes(forCharacterIndex: 0,
                                  lineHeightRectangle: &lineRect)
        return lineRect
    }
}
