import Foundation
import InputMethodKit
import LingoPulseIMECore

// LingoPulseIMEController intercepts keystrokes via InputMethodKit's keybinding
// approach (approach 1): printable text arrives via inputText(_:client:) and
// commands (Enter, Escape, arrows, Backspace) arrive via didCommand(by:client:).
// All events are passed through (return false) so the host application receives
// them unchanged. The only side-effect is maintaining a TypingSession buffer so
// that Phase 3 can trigger the daemon when enough words accumulate.
@objc(LingoPulseIMEController)
final class LingoPulseIMEController: IMKInputController {

    // MARK: - State

    private var session = TypingSession()

    // MARK: - Lifecycle

    override init!(server: IMKServer!, delegate: Any!, client inputClient: Any!) {
        super.init(server: server, delegate: delegate, client: inputClient)
    }

    override func activateServer(_ sender: Any!) {
        session.reset()
    }

    override func deactivateServer(_ sender: Any!) {
        session.reset()
    }

    // MARK: - IMKServerInput (keybinding approach)

    /// Receives printable characters that did not map to a keybinding action.
    /// Returns false so the character is passed through to the active application.
    override func inputText(_ string: String!, client sender: Any!) -> Bool {
        guard let text = string, !text.isEmpty else { return false }
        session.append(text)
        return false
    }

    /// Receives special-key commands generated by the system keybinding table
    /// (e.g. insertNewline:, deleteBackward:, moveLeft:).
    /// Resets the session buffer for navigation/commit/cancel actions and
    /// returns false so the key is passed through to the active application.
    override func didCommand(by aSelector: Selector!, client sender: Any!) -> Bool {
        switch aSelector {
        case #selector(NSResponder.insertNewline(_:)),            // Return
             #selector(NSResponder.insertLineBreak(_:)),          // Shift-Return in some apps
             #selector(NSResponder.cancelOperation(_:)),          // Escape
             #selector(NSResponder.deleteBackward(_:)),           // Backspace
             #selector(NSResponder.deleteForward(_:)),            // Delete (fn-Backspace)
             #selector(NSResponder.moveLeft(_:)),                 // Left arrow
             #selector(NSResponder.moveRight(_:)),                // Right arrow
             #selector(NSResponder.moveUp(_:)),                   // Up arrow
             #selector(NSResponder.moveDown(_:)),                 // Down arrow
             #selector(NSResponder.moveToBeginningOfLine(_:)),    // Cmd-Left / Home
             #selector(NSResponder.moveToEndOfLine(_:)),          // Cmd-Right / End
             #selector(NSResponder.moveToBeginningOfDocument(_:)),
             #selector(NSResponder.moveToEndOfDocument(_:)):
            session.reset()
        default:
            break
        }
        return false
    }

    override func commitComposition(_ sender: Any!) {
        session.reset()
    }
}
